---
# tasks file for packages

- name: Download Microsoft package configuration
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/{{ ansible_facts['lsb']['id']|lower }}/{{ ansible_facts['lsb']['release'] }}/packages-microsoft-prod.deb"
    dest: "/tmp/packages-microsoft-prod.deb"
    force: false
    use_proxy: true
    validate_certs: true
    mode: "u=rw,go=r"

- name: Install Microsoft package configuration
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb
    state: present
  become: true
  become_method: ansible.builtin.sudo
  when: not ansible_check_mode

- name: update package list
  become: true
  package:
    update_cache: true

- name: "Upgrade all packages"
  apt:
    upgrade: true
    force_apt_get: true
  become: true
  become_method: sudo

- name: Install packages
  become: true
  apt:
    name: "{{ prerequisite_packages }}"
