---
# tasks file for packages
# - ansible.builtin.import_tasks: microsoft-repo.yml // This is might not be needed with official dotnet versions (part of regular repositories)

- name: update package list
  become: true
  package:
    update_cache: true

- name: "Upgrade all packages"
  apt:
    upgrade: true
    force_apt_get: true
  become: true
  become_method: sudo

- name: Install packages
  become: true
  apt:
    name: "{{ prerequisite_packages }}"
