---
- name: Download and install Microsoft repository
  block:
    - name: Download Microsoft package configuration
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/config/{{ ansible_facts['lsb']['id']|lower }}/{{ ansible_facts['lsb']['release'] }}/packages-microsoft-prod.deb"
        dest: "/tmp/packages-microsoft-prod.deb"
        force: false
        use_proxy: true
        validate_certs: true
        mode: "u=rw,go=r"

    - name: Install Microsoft package configuration
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb
        state: present
    - name: Cleanup Microsoft package configuration
      ansible.builtin.file:
        path: /tmp/packages-microsoft-prod.deb
        state: absent
  become: true
  become_method: ansible.builtin.sudo
  when: not ansible_check_mode
