---
- name: "Install Tmux plugins (remember to do Prefix+I to install plugins once Tmux is running)"
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: "Copying dotfiles"
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}"
  with_items:
    - ".tmux.conf"
    - ".bashrc"
    - ".bash_aliases"
