---
# defaults file for dev
# Go language SDK version number
golang_version: '1.21.0'
golang_redis_sha256sum: d0398903a16ba2232b389fb31032ddf57cac34efda306a0eebac34f0965a0742

# Architecture of the Go redistributable
golang_architecture: amd64


# Mirror to download the Go language SDK redistributable package from
golang_mirror: 'https://storage.googleapis.com/golang'

# Base installation directory the Go language SDK distribution
golang_install_dir: '/opt/go/{{ golang_version }}'

# Directory to store files downloaded for Go language SDK installation
golang_download_dir: "{{ x_ansible_download_dir | default(ansible_facts.env.HOME + '/.ansible/tmp/downloads') }}"

# Filename of Go language SDK redistributable package
golang_redis_filename: 'go{{ golang_version }}.linux-{{ golang_architecture }}.tar.gz'

# Location for GOPATH environment variable
golang_gopath:
