---
- name: "Check if 1Password CLI is already installed"
  stat:
    path: /usr/bin/op
  register: op_installed

- name: "Download & Install 1Password CLI"
  when: not op_installed.stat.exists
  block:
    - name: "Retrieve the key for the 1Password apt repository"
      get_url:
        url: "https://downloads.1password.com/linux/keys/1password.asc"
        dest: /tmp/1password.asc
    - name: "Add the 1Password apt repository key"
      shell: "gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg /tmp/1password.asc"
      args:
        creates: "/usr/share/keyrings/1password-archive-keyring.gpg"
    - name: "Add the 1Password apt repository"
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
        state: present
    - name: "Add debsig-verify policy"
      shell: "{{ item }}"
      args:
        creates: "/etc/debsig/policies/AC2D62742012EA22/1password.pol"
      with_items:
        - mkdir -p /etc/debsig/policies/AC2D62742012EA22/
        - curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
        - mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
        - curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    - name: "Install 1Password CLI"
      apt:
        name: "1password-cli"
        state: present
        update_cache: yes
    - name: "1Password cleanup"
      file:
        path: /tmp/1password.asc
        state: absent
  become: true
  become_method: sudo
